version: "3"
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - efk

  fluentd:
    #    build: ./fluentd
    image: fluentd:v1
    container_name: fluentd-server
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /data/elastic/certs/ca:/fluentd/certs/ca
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk

networks:
  efk:
    external: true
    name: efk
