version: "3"
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - efk

  fluentd:
    #    build: ./fluentd
    image: fluentd:v1
    container_name: fluentd-server
    environment:
      - TZ=Asia/Tehran
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /data/elastic/certs/ca:/fluentd/certs/ca
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "24225:24225"
    healthcheck:
      test: curl --fail -s http://localhost:24225 || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s
    networks:
      - efk

networks:
  efk:
    external: true
    name: efk
